version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mysql-data: