version: '3'

services:
  deploy_test_freestyle:
    build:
      context: .
      dockerfile: ./DeployStudy/Dockerfile
    ports:
      - 8080:8080
    networks:
      - spring-network

networks:
  spring-network:

volumes:
  mysql-data: